### ISSUE TITLE
Is the project stalled?

### ISSUE THREAD

**Issue by affansyed** [adrianwalker/cassandra-filesystem#1]
Seems like a great idea, that got stalled. Any community effort around this?

**Comment by adrianwalker** [comment]
Hi Affan

I'm not actively developing this anymore and there has been no community interest that I am aware of.

If you wanted some further information about the project, I have a short blog post here:
http://www.adrianwalker.org/2017/09/another-apache-cassandra-file-system.html

And another project which uses this code as the backing file system for a FTP server:
http://www.adrianwalker.org/2017/09/ftp-files-into-apache-cassandra-with.html

This code is Public Domain, please feel free to use, modify and distribute my code in any way you like without any restrictions.
